use_frameworks!

platform :ios, '9.0'

target 'RandomDataGenerator_Example' do
  pod 'RandomDataGenerator', :path => '../'

  target 'RandomDataGenerator_Tests' do
    inherit! :search_paths

    
  end
end
